### ISSUE TITLE
Changing colour of icons?

### ISSUE THREAD

**Issue by riannazandbelt** [riannazandbelt/svg-icon-sets#1]
Hi @hellachella and @jessjodoin,

I'm unsure what I should be targeting to change the colour of the icons. I've tried targeting them individually as well as a group (mars-icons.svg) but I've been unsuccessful thus far. Any tips?

Thanks!

**Comment by JessJodoin** [comment]
Target the `<i>` and `<svg>` tags and change their fill
```
i svg {
  fill: #fff;
}
```
